[0m14:06:52.017547 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086fbe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108710d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108711650>]}


============================== 14:06:52.020534 | cd76d35d-b7d8-4000-aa00-d62bf92a56b7 ==============================
[0m14:06:52.020534 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:06:52.020836 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt run-operation debug_vars --profiles-dir .', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:06:52.021138 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafazaki/Documents/Mammoth Data Pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:06:52.057479 [debug] [MainThread]: Resource report: {"command_name": "run-operation", "command_success": false, "command_wall_clock_time": 0.080759086, "process_in_blocks": "0", "process_kernel_time": 0.20916, "process_mem_max_rss": "109707264", "process_out_blocks": "0", "process_user_time": 0.697107}
[0m14:06:52.057822 [debug] [MainThread]: Command `dbt run-operation` failed at 14:06:52.057758 after 0.08 seconds
[0m14:06:52.058081 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108710710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108710cd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100d36910>]}
[0m14:06:52.058306 [debug] [MainThread]: Flushing usage events
[0m14:06:52.416446 [debug] [MainThread]: An error was encountered while trying to flush usage events
